# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmarterBarter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='semester',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
