# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmarterBarter', '0004_auto_20151229_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='copiesLeft',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
