# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmarterBarter', '0005_book_copiesleft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='copiesLeft',
            field=models.IntegerField(default=0),
        ),
    ]
