# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmarterBarter', '0006_auto_20151230_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='currentRequests',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='noOfRequests',
            field=models.IntegerField(default=0),
        ),
    ]
