# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmarterBarter', '0008_auto_20151231_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApproveRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookName', models.CharField(max_length=200)),
                ('requested_by', models.CharField(max_length=100)),
            ],
        ),
    ]
