# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmarterBarter', '0010_approverequests_issued'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookName', models.CharField(max_length=200)),
                ('requested_by', models.CharField(max_length=100)),
            ],
        ),
    ]
