# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmarterBarter', '0011_approvedrequests'),
    ]

    operations = [
        migrations.AddField(
            model_name='approverequests',
            name='bookId',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
