# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmarterBarter', '0012_approverequests_bookid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='superuser',
            field=models.IntegerField(default=0),
        ),
    ]
