# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmarterBarter', '0013_userprofile_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvedrequests',
            name='bookId',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
